//菜单1，按钮2
let data = [
  {
    alias: "space",
    checked: false,
    category: 1,
    level: 0,
    parent_id: null,
    children: [
      {
        alias: "view",
        checked: false,
        category: 2,
        children: null,
        code: "space-view",
        hide_in_menu: false,
        id: 2,
        name: "查看",
        level: 1,
        parent_id: 1,
      },
      {
        alias: "add",
        checked: false,
        category: 2,
        children: null,
        code: "space-add",
        hide_in_menu: false,
        id: 3,
        name: "新建",
        level: 1,
        parent_id: 1,
      },
      {
        alias: "edit",
        checked: false,
        category: 2,
        children: null,
        code: "space-edit",
        hide_in_menu: false,
        id: 4,
        name: "编辑",
        level: 1,
        parent_id: 1,
      },
      {
        alias: "detail",
        checked: false,
        category: 1,
        level: 1,
        parent_id: 1,
        id: 5,
        children: [
          {
            alias: "view",
            checked: false,
            category: 2,
            children: null,
            code: "space-detail-view",
            hide_in_menu: false,
            id: 29,
            name: "查看",
            level: 2,
            parent_id: 5,
          },
          {
            alias: "edit",
            checked: false,
            category: 2,
            children: null,
            code: "space-detail-edit",
            hide_in_menu: false,
            id: 6,
            name: "编辑",
            level: 2,
            parent_id: 5,
          },
        ],
        code: "space-detail",
        hide_in_menu: false,
        name: "空间详情",
      },
      {
        alias: "draw-board",
        checked: false,
        category: 1,
        level: 1,
        parent_id: 1,
        id: 15,
        children: [
          {
            alias: "draw-board-list",
            checked: false,
            category: 1,
            level: 2,
            code: "space-draw-board-list",
            hide_in_menu: false,
            id: 16,
            name: "空间画板列表",
            parent_id: 15,
            children: [
              {
                alias: "view",
                checked: false,
                category: 2,
                children: null,
                code: "space-draw-board-list-view",
                hide_in_menu: false,
                id: 28,
                name: "查看",
                level: 3,
                parent_id: 16,
              },
              {
                alias: "add",
                checked: false,
                category: 2,
                children: null,
                code: "space-draw-board-list-add",
                hide_in_menu: false,
                id: 17,
                name: "新建",
                level: 3,
                parent_id: 16,
              },
              {
                alias: "edit",
                checked: false,
                category: 2,
                children: null,
                code: "space-draw-board-list-edit",
                hide_in_menu: false,
                id: 18,
                name: "编辑",
                level: 3,
                parent_id: 16,
              },
            ],
          },
          {
            alias: "draw-board-config",
            checked: false,
            category: 1,
            level: 2,
            code: "space-draw-board-config",
            hide_in_menu: false,
            id: 19,
            name: "空间画板配置",
            parent_id: 15,
            children: [
              {
                alias: "view",
                checked: false,
                category: 2,
                children: null,
                code: "space-draw-board-config-view",
                hide_in_menu: false,
                id: 27,
                name: "查看",
                level: 3,
                parent_id: 19,
              },
              {
                alias: "add",
                checked: false,
                category: 2,
                children: null,
                code: "space-draw-board-config-add",
                hide_in_menu: false,
                id: 20,
                name: "新建",
                level: 3,
                parent_id: 19,
              },
              {
                alias: "edit",
                checked: false,
                category: 2,
                children: null,
                code: "space-draw-board-config-edit",
                hide_in_menu: false,
                id: 21,
                name: "编辑",
                level: 3,
                parent_id: 19,
              },
              {
                alias: "drag",
                checked: false,
                category: 1,
                parent_id: 19,
                children: [
                  {
                    alias: "top",
                    checked: false,
                    category: 2,
                    children: null,
                    code: "space-draw-board-config-drag-top",
                    hide_in_menu: false,
                    id: 23,
                    name: "向上",
                    level: 4,
                    parent_id: 22,
                  },
                  {
                    alias: "bottom",
                    checked: false,
                    category: 2,
                    children: null,
                    code: "space-draw-board-config-drag-bottom",
                    hide_in_menu: false,
                    id: 24,
                    name: "向下",
                    level: 4,
                    parent_id: 22,
                  },
                  {
                    alias: "left",
                    checked: false,
                    category: 2,
                    children: null,
                    code: "space-draw-board-config-drag-left",
                    hide_in_menu: false,
                    id: 25,
                    name: "向左",
                    level: 4,
                    parent_id: 22,
                  },
                  {
                    alias: "right",
                    checked: false,
                    category: 2,
                    children: null,
                    code: "space-draw-board-config-drag-right",
                    hide_in_menu: false,
                    id: 26,
                    name: "向右",
                    level: 4,
                    parent_id: 22,
                  },
                ],
                code: "space-draw-board-config-drag",
                hide_in_menu: false,
                id: 22,
                name: "画布拖拽",
                level: 3,
              },
            ],
          },
        ],
        code: "space-draw-board",
        hide_in_menu: false,
        name: "空间画板",
      },
    ],
    code: "space",
    hide_in_menu: false,
    id: 1,
    name: "空间列表",
  },
  {
    alias: "design-space",
    checked: false,
    category: 1,
    level: 0,
    parent_id: null,
    children: [
      {
        alias: "view",
        checked: false,
        category: 2,
        children: null,
        code: "design-view",
        hide_in_menu: false,
        id: 8,
        name: "查看",
        level: 1,
        parent_id: 7,
      },
      {
        alias: "add",
        checked: false,
        category: 2,
        children: null,
        code: "design-add",
        hide_in_menu: false,
        id: 9,
        name: "新建",
        level: 1,
        parent_id: 7,
      },
      {
        alias: "edit",
        checked: false,
        category: 2,
        children: null,
        code: "design-edit",
        hide_in_menu: false,
        id: 10,
        name: "编辑",
        level: 1,
        parent_id: 7,
      },
    ],
    code: "design-space",
    hide_in_menu: false,
    id: 7,
    name: "设计工坊",
  },
  {
    alias: "design-hall",
    checked: false,
    category: 1,
    level: 0,
    parent_id: null,
    children: [
      {
        alias: "view",
        checked: false,
        category: 2,
        children: null,
        code: "design-hall-view",
        hide_in_menu: false,
        id: 12,
        name: "查看",
        level: 1,
        parent_id: 11,
      },
      {
        alias: "add",
        checked: false,
        category: 2,
        children: null,
        code: "design-hall-add",
        hide_in_menu: false,
        id: 13,
        name: "新建",
        level: 1,
        parent_id: 11,
      },
      {
        alias: "edit",
        checked: false,
        category: 2,
        children: null,
        code: "design-hall-edit",
        hide_in_menu: false,
        id: 14,
        name: "编辑",
        level: 1,
        parent_id: 11,
      },
    ],
    code: "design-hall",
    hide_in_menu: false,
    id: 11,
    name: "设计展厅",
  },
];
export default data;

// 空间列表、用户管理、数据中心（数据源，数据集）、设计工坊、数据展厅、
// 回收站（软删除内容会在回收站中展示，只有在回收站中再次删除才会彻底删除）、运维管理、素材市场、模版市场、自定义和dashboard设计器
